<?php

use CRM_Identitytracker_ExtensionUtil as E;

return [
  [
    'name' => 'CustomGroup__contact_id_history',
    'entity' => 'CustomGroup',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => CRM_Identitytracker_Configuration::GROUP_NAME,
        'title' => E::ts('Contact Identities'),
        'extends' => 'Contact',
        'table_name' => CRM_Identitytracker_Configuration::GROUP_TABLE,
        'style' => 'Tab with table',
        'help_pre' => E::ts('This is a list of all the IDs this contact ever had, even across merging duplicates.'),
        'is_active' => TRUE,
        'is_multiple' => TRUE,
        'collapse_display' => FALSE,
        'collapse_adv_display' => FALSE,
        'is_reserved' => FALSE,
        'is_public' => TRUE,
        'icon' => 'fa-id-card',
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionGroup__contact_id_history_type',
    'entity' => 'OptionGroup',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => CRM_Identitytracker_Configuration::TYPE_GROUP_NAME,
        'title' => E::ts('Contact Identity Types'),
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'option_value_fields' => [
          'name',
          'label',
          'description',
        ],
      ],
      'match' => [
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionValue__contact_id_history_type__internal',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'contact_id_history_type',
        'label' => E::ts('CiviCRM ID'),
        'value' => CRM_Identitytracker_Configuration::TYPE_INTERNAL,
        'name' => CRM_Identitytracker_Configuration::TYPE_INTERNAL,
        'is_default' => FALSE,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'icon' => 'fa-user',
      ],
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'OptionValue__contact_id_history_type__external',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'option_group_id.name' => 'contact_id_history_type',
        'label' => E::ts('External Identifier'),
        'value' => CRM_Identitytracker_Configuration::TYPE_EXTERNAL,
        'name' => CRM_Identitytracker_Configuration::TYPE_EXTERNAL,
        'is_default' => TRUE,
        'is_reserved' => TRUE,
        'is_active' => TRUE,
        'icon' => 'fa-user-circle',
      ],
      'match' => [
        'option_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomField__contact_id_history__id_history_entry_type',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => CRM_Identitytracker_Configuration::GROUP_NAME,
        'name' => CRM_Identitytracker_Configuration::TYPE_FIELD_NAME,
        'label' => E::ts('ID Type'),
        'data_type' => 'String',
        'html_type' => 'Select',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'column_name' => CRM_Identitytracker_Configuration::TYPE_FIELD_COLUMN,
        'option_group_id.name' => CRM_Identitytracker_Configuration::TYPE_GROUP_NAME,
        'in_selector' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomField__contact_id_history__id_history_entry',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => CRM_Identitytracker_Configuration::GROUP_NAME,
        'name' => CRM_Identitytracker_Configuration::ID_FIELD_NAME,
        'label' => E::ts('Identifier'),
        'data_type' => 'String',
        'html_type' => 'Text',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => FALSE,
        'is_view' => FALSE,
        'column_name' => CRM_Identitytracker_Configuration::ID_FIELD_COLUMN,
        'in_selector' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomField__contact_id_history__id_history_date',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => CRM_Identitytracker_Configuration::GROUP_NAME,
        'name' => CRM_Identitytracker_Configuration::DATE_FIELD_NAME,
        'label' => E::ts('Used since'),
        'data_type' => 'Date',
        'html_type' => 'Select Date',
        'is_required' => TRUE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_active' => TRUE,
        'is_view' => FALSE,
        'date_format' => 'yy-mm-dd',
        'time_format' => 2,
        'column_name' => CRM_Identitytracker_Configuration::DATE_FIELD_COLUMN,
        'in_selector' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'CustomField__contact_id_history__id_history_context',
    'entity' => 'CustomField',
    'cleanup' => 'never',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'custom_group_id.name' => CRM_Identitytracker_Configuration::GROUP_NAME,
        'name' => CRM_Identitytracker_Configuration::CONTEXT_FIELD_NAME,
        'label' => E::ts('Context'),
        'data_type' => 'String',
        'html_type' => 'Text',
        'is_required' => FALSE,
        'is_searchable' => TRUE,
        'is_search_range' => TRUE,
        'is_active' => FALSE,
        'is_view' => FALSE,
        'column_name' => CRM_Identitytracker_Configuration::CONTEXT_FIELD_COLUMN,
        'in_selector' => TRUE,
      ],
      'match' => [
        'custom_group_id',
        'name',
      ],
    ],
  ],
];

